### ISSUE TITLE
Implement driver for tm1814 RGBW LED 

### ISSUE THREAD

**Issue by HendrikSchmi** [saleae/async-rgb-led-analyzer#8]
Hello all,

Could someone still adapt the decoder for the TM1814 IC?

The datasheet is attached.
[TM1814-TitanMicro.pdf](https://github.com/saleae/async-rgb-led-analyzer/files/12239689/TM1814-TitanMicro.pdf)

Thanks in advance

**Comment by timreyes** [comment]
@HendrikSchmi Thanks for reaching out! We generally reserve the Issues section for our GitHub repos for bugs. Because of this, I'll close this issue for now.

Having said that, I do want to make sure your request is properly recorded! As such, I'd suggest you to post your feature request on our ideas site below:
https://ideas.saleae.com/b/feature-requests/

Alternatively, I wanted to let you know that we currently don't have the resources to help with implementing this internally. Our software team (4 members at the moment) is laser focused on other priorities. 

In case you are unable to implement the changes via your own custom analyzer or extension to meet your requirements, we're working with the folks at Binho to provide services to develop custom extensions. More information on this can be found in the link below in case you are interested in reaching out to them!
https://binho.io/pages/custom-protocol-analyzer-development
